feed/urls.py
from django.conf.urls import include
from django.urls import path
from . import views


app_name = 'article'

urlpatterns = [
    path(r'', views.FeedsView.as_view(), name='feed'),
    path(r'<int:pk>', views.DetailView.as_view(), name='details'),
    #url(r'^logout/$', views.logout, name='logout'),
    path(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

kevinngetich/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'kevinngetich'

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^logout/$', views.logout, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    #url(r'', views.login.as_view(), name='login'),
    url(r'^feed/', include('feed.urls'), name='feed'),

    #url(r'^login/$', views.Home.as_view, name='login'),
    #url('', views.home.as_view(), name='home'),
    #url(r'^auth/', include('social_django.urls', namespace='social')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.urls import reverse
import datetime


# Create your models here.

class Article(models.Model):
    article_title = models.CharField(max_length=250)
    article_text = models.TextField(default="A bunch of Stuff")
    article_summary = models.CharField(max_length=110)
    article_author = models.CharField(max_length=250)
    article_created = models.DateField(default=datetime.date.today)
    article_last_update = models.DateField(default=datetime.date.today)
    article_upvotes = models.IntegerField(default=0)
    article_downvotes = models.IntegerField(default=0)
    article_comments = models.IntegerField(default=0)
    article_views = models.IntegerField(default=0)
    article_tags = models.CharField(max_length=250, default="#code")
    image = models.FileField(default=None)

    def get_absolute_url(self):
        return reverse('article:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.pk) + "-" + self.article_title

class Comments(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    user = models.CharField(max_length=250)
    comment = models.TextField(default="A bunch of Stuff")
    comment_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.comment

feed/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms

class CommentForm(forms.Form):
    article = forms.CharField(widget = forms.HiddenInput())
    username = forms.CharField(widget = forms.HiddenInput())
    comment = forms.CharField(widget=forms.Textarea)

comments/views.py
from django.shortcuts import render

# Create your views here.

feed/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from article.models import Article, Comments
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect
from article.forms import CommentForm
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render




class FeedsView(generic.ListView):
    template_name = 'feed/index.html'
    context_object_name = 'all_articles'

    def get_queryset(self):
        return Article.objects.all()

class DetailView(generic.DetailView):
    context_object_name = 'article'
    template_name = 'article/article.html'
    form_class = CommentForm
    #queryset = Article.objects.all()
    model = Article

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['comments'] = Comments.objects.all()
        #context['form'] = self.form_class
        return context

    def post(self, request, pk):
        #form = CommentForm(request.POST)

        if request.method == 'POST':
            article_id = request.POST.get('article')
            user_id = request.POST.get('user', False)
            commenttxt = request.POST.get('comment', False)
            print("User ID is: " + str(user_id))
            print("Comment is: " + str(commenttxt))
            print("Article is: " + str(article_id))
            articleinst = Article.objects.get(pk=article_id)
            newcomment = Comments()
            newcomment.article = articleinst
            newcomment.user = user_id
            newcomment.comment = commenttxt
            newcomment.save()
        return super().get(request)


def logout(request):
    auth_logout(request)
    return redirect('/')

class ArticleCreate(CreateView):
    model = Article
    fields = ['article_title', 'article_text', 'article_image']

class ArticleUpdate(UpdateView):
    model = Article
    fields = ['article_title', 'article_text', 'article_image']

class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('feed:index')

    def get(self, request, *args, **kwargs):
        return self.Article(request, *args, **kwargs)

kevinngetich/views.py
from django.views.generic import TemplateView
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render, redirect

class home(TemplateView):
    template_name = 'home.html'

class login(TemplateView):
    template_name = 'login.html'

def logout(request):
    auth_logout(request)
    return redirect('/feed')

article/templates/article/article.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
Article
{% endblock %}

{% block content %}
            <div class="col-lg-6">
                <div class="card card-default">

                    <div class="card-body" style="padding-bottom: 15px; padding-left: 10px; padding-right: 10px;">

                        <h1 class="card-title" style="text-align: center;"><strong>{{ article.article_title }}</strong></h1>
                        <img class="card-img-top" src="{{ article.image.url }}" alt="{{ article.article_title }}" style="padding-right: 15px;">
                        <hr>
                      <p class="card-text" style="text-align: justify; letter-spacing: 2px; font-size: 100%;"> {{ article.article_text | linebreaks }} </p>
                    </div>
                </div>

                <hr>
                <h3 style="text-align: center;"><strong>Comments</strong></h3>
                <hr>
                {% if user.is_authenticated %}
                <form method="post">
                    {% csrf_token %}
                  <div class="form-group">
                      <label for="comment">Comment as {{ user.username }}: </label>
                      <textarea type="text" class="form-control" name="comment" placeholder="Commment"></textarea>
                      <input type="hidden" class="form-control" name="article" value="{{ article.id }}">
                      <input type="hidden" class="form-control" name="user" value="{{ user.username }}">
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <hr>
                {% else %}
                <h4 style="text-align: center;">Sign Up to Comment</h4>
                <br>
                {% endif %}
                {% if comments %}
                    {% for comment in comments %}
                        {% if comment.article.id is article.id %}
                            <div class="card card-main">
                                <div class="card-body" style="padding-bottom: 15px;">
                                    <h3 class="card-title" style="text-align: justify;"><strong>{{ comment.user }}</strong></h3>
                                  <p class="card-text">{{ comment.comment }}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <h1 style="text-align: center;">THERE ARE NO COMMENTS TO VIEW</h1>
                {% endif %}
                <hr>
            </div>
{% endblock %}

feed/templates/feed/index.html
{% extends 'base.html' %}


{% block title %}
Feeds
{% endblock %}

{% block content %}
            <div class="col-lg-6">
                {% if all_articles %}
                    {% for article in all_articles %}

                        <div class="card card-main">
                            <img class="card-img-top" src="{{ article.image.url }}" alt="Card image cap">
                            <div class="card-body" style="padding-bottom: 15px;">
                                <h3 class="card-title" style="text-align: justify;"><strong>{{ article.article_title }}</strong></h3>
                              <p class="card-text">{{ article.article_summary }}</p>
                              <p class="card-text card-info"><small class="text-muted">Last updated: {{ article.article_last_update }} <a class="btn btn-default" href="{% url 'article:details' article.id %}" style="margin-left: 300px;"> Read Article... </a> </small></p>

                            </div>
                        </div>
                        &nbsp;
                        &nbsp;
                    {% endfor %}
                {% else %}
                    <h1 style="text-align: center;">THERE ARE NO ARTICLES TO VIEW</h1>
                {% endif %}
            </div>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <title>Kevin Ngetich | {% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static './css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './style1.css' %}"-->

</head>
<body style="font-size: 1.8em;">
    <script src="{% static './js/boostrap.js' %}"></script>
    <script src="{% static './js/boostrap.min.js' %}"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <div class="container-fluid" style="font-size: 80%;">
        <nav class="navbar navbar-default bg-dark navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> <strong>Showcase</strong> </a>
            </div>
            <div class="collapse navbar-collapse" id=#navigation>
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a class="nav-link" href="{% url 'article:feed' %}"><strong>Feed</strong></a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input class="form-control mr-sm-2" type="text" name="q" value="" placeholder="Search">
                    </div>
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a class="nav-pill"><strong>{{ user.username }}</strong></a>
                        </li>
                        <LI>
                            <a class="nav-link" href="{% url 'logout' %}"><strong>Log Out </strong>&nbsp;
                            <span class="glyphicon glyphicon-off"></span></a>
                        </LI>
                        &nbsp;
                        &nbsp;
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a class="nav-link" href="{% url 'social:begin' 'github' %}"><strong>Log in with GitHub</strong></a>
                        </li>
                    </ul>
                {% endif %}
            </div>

        </nav>
    </div>
    <div class="container-fluid" style="font-size: 90%;">
        <div class="row" style="margin-top: 70px;">
            <div class="col-lg-3">
                <br>
                <img class="img-fluid" src="/media/python1.png" alt="Author's Image" style="height: 200px; display: block; margin-left: auto; margin-right: auto">

            </div>
            {% block content %}
            {% endblock %}
            <div class="col-lg-3">

                <div class="card card-default" style="background: 	#F8F8F8;">
                    <div class="card-body" style="padding-bottom: 2px;">
                      <h2 class="card-title" style="text-align: center;"><strong> Featured </strong></h2>
                    </div>
                </div>
                <br>
                <div class="card card-default" style="">

                    <div class="card-body" style="padding-top: 15px;">

                        <h4 class="card-text"> <img src="/media/access-blur-close-up-1181271.jpg" style="height: 60px; width: 60px;" > &nbsp; Something About... </h4>
                        <hr>
                        <h4 class="card-text"> <img src="/media/blur-code-coding-270408.jpg" style="height: 60px; width: 60px;"> &nbsp; Django vs Laravel </h4>
                        <hr>
                        <h4 class="card-text"> <img src="/media/backlit-blogging-coding-34153.jpg" style="height: 60px; width: 60px;"> &nbsp; My Python Journey </h4>
                        <br>
                    </div>
                </div>

            </div>
        </div>
    </div>
</body>
</html>

templates/home.html
{% if user.is_authenticated %}
    <p class="display-4">Hello, {{ user.username }}</p>
    <a class="lead" href="{% url 'logout' %}">Log Out</a>

{% else %}
    <a class="lead" href="{% url 'login' %}">Log in</a>
{% endif %}

templates/login.html
{% if user.is_authenticated %}
    <p class="display-4">Hello, {{ user.username }}</p>
    <a class="lead" href="{% url 'logout' %}">Log Out</a>

{% else %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

    <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
{% endif %}

templates/logout.html
{% url "socialauth_disconnect" "backend-name" %}

templates/under-construction.html
<!DOCTYPE HTML>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <title>Kevin Ngetich | {% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static './css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/boostrap.theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './style.css' %}">

</head>
<body>
    <script src="{% static './js/boostrap.js' %}"></script>
    <script src="{% static './js/boostrap.min.js' %}"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <div class="container-fluid">
        <nav class="navbar navbar-default bg-dark navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Converse </a>
            </div>
            <div class="collapse navbar-collapse" id=#navigation>
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a class="nav-link" href="{% url 'article:feed' %}">Feed</a>
                    </li>

                    <li class="">
                        <a class="nav-link" href="#">Messages</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input class="form-control mr-sm-2" type="text" name="q" value="" placeholder="Search">
                    </div>
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <ul class="nav navbar-nav">
                    <li class="">
                        <a class="nav-link" href="#">About</a>
                    </li>

                    <li class="">
                        <a class="nav-link" href="#">
                            Logout&nbsp;
                            <span class="glyphicon glyphicon-off"></span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container-fluid">
        <div class="row" style="margin-top: 70px;">
            <div class="col-lg-12">
                <h1>WEBSITE IS UNDER CONSTRUCTION. WILL BE AVAILABLE SOON.</h1>
            </div>
        </div>
    </div>
</body>
</html>